const catalog = [
    {
        id: 'elem1',
        img: 'img/catalog/Alexandro.webp',
        name: 'Алехандро Крим 0.75мл',
        country: 'Испания / 18%',
        price: 1399,
    },
    {
        id: 'elem2',
        img: 'img/catalog/Berfut.webp',
        name: 'Берфут Зинфандель',
        country: 'Красное п.сухое / США / 13.5%',
        price: 1224,
    },
    {
        id: 'elem3',
        img: 'img/catalog/Byve.webp',
        name: 'Буве Брют',
        country: 'Белое брют / Франция / 12.5%',
        price: 1499,
    },
    {
        id: 'elem4',
        img: 'img/catalog/Alexandro.webp',
        name: 'Алехандро Крим 0.75мл',
        country: 'Испания / 18%',
        price: 1399,
    },
    {
        id: 'elem5',
        img: 'img/catalog/Berfut.webp',
        name: 'Берфут Зинфандель',
        country: 'Красное п.сухое / США / 13.5%',
        price: 1224,
    },
    {
        id: 'elem6',
        img: 'img/catalog/Byve.webp',
        name: 'Буве Брют',
        country: 'Белое брют / Франция / 12.5%',
        price: 1499,
    },
    {
        id: 'elem7',
        img: 'img/catalog/Alexandro.webp',
        name: 'Алехандро Крим 0.75мл',
        country: 'Испания / 18%',
        price: 1399,
    },
    {
        id: 'elem8',
        img: 'img/catalog/Berfut.webp',
        name: 'Берфут Зинфандель',
        country: 'Красное п.сухое / США / 13.5%',
        price: 1224,
    },
    {
        id: 'elem9',
        img: 'img/catalog/Byve.webp',
        name: 'Буве Брют',
        country: 'Белое брют / Франция / 12.5%',
        price: 1499,
    },
]